# Form implementation generated from reading ui file 'file_ui/themhocvien.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1152, 774)
        self.widget_2 = QtWidgets.QWidget(parent=Dialog)
        self.widget_2.setGeometry(QtCore.QRect(0, 0, 1161, 771))
        self.widget_2.setStyleSheet("background: white;\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.themhv = QtWidgets.QTableWidget(parent=self.widget_2)
        self.themhv.setGeometry(QtCore.QRect(30, 170, 1101, 511))
        self.themhv.setStyleSheet("QTableWidget {\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    background-color: white;\n"
"    alternate-background-color:#ffecee;\n"
"    gridline-color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"")
        self.themhv.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.themhv.setProperty("showDropIndicator", True)
        self.themhv.setDragDropOverwriteMode(True)
        self.themhv.setAlternatingRowColors(True)
        self.themhv.setShowGrid(True)
        self.themhv.setObjectName("themhv")
        self.themhv.setColumnCount(9)
        self.themhv.setRowCount(29)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.themhv.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.themhv.setItem(0, 0, item)
        self.themhv.horizontalHeader().setDefaultSectionSize(110)
        self.themhv.horizontalHeader().setSortIndicatorShown(False)
        self.themhv.horizontalHeader().setStretchLastSection(True)
        self.themhv.verticalHeader().setVisible(False)
        self.themhv.verticalHeader().setDefaultSectionSize(37)
        self.themhv.verticalHeader().setSortIndicatorShown(False)
        self.label_12 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_12.setGeometry(QtCore.QRect(420, 70, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.Button_return = QtWidgets.QPushButton(parent=self.widget_2)
        self.Button_return.setGeometry(QtCore.QRect(30, 70, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_return.setFont(font)
        self.Button_return.setStyleSheet("QPushButton {\n"
"    /* Màu nền và viền */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 8px; /* Tăng bo góc một chút cho hợp với chữ to */\n"
"    \n"
"    /* Chữ: In đậm, Cỡ 25pt, Font Segoe UI */\n"
"    color: #bc1823;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    \n"
"    /* Đệm thêm khoảng trống xung quanh chữ */\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8d7da;\n"
"    border: 2px solid #bc1823; /* Viền dày hơn khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        icon = QtGui.QIcon.fromTheme("\\u2b05")
        self.Button_return.setIcon(icon)
        self.Button_return.setIconSize(QtCore.QSize(25, 25))
        self.Button_return.setObjectName("Button_return")
        self.label_quanlyhocvien_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_quanlyhocvien_2.setGeometry(QtCore.QRect(0, 20, 1161, 41))
        self.label_quanlyhocvien_2.setStyleSheet("QLabel {\n"
"    /* Màu nền đỏ đậm thương hiệu của Trầm */\n"
"    background-color: #bc1823;\n"
"    \n"
"    /* Chữ trắng, in hoa và đậm (Bold 700) */\n"
"    color: white;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"    \n"
"    /* Bo góc và viền để khớp với Dashboard */\n"
"    border-radius: 8px;\n"
"    border: 1px solid #bc1823;\n"
"    \n"
"    /* Căn giữa chữ tuyệt đối */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột vào để giao diện sinh động hơn */\n"
"QLabel:hover {\n"
"    background-color: #ffecee; /* Đổi sang nền hồng nhạt */\n"
"    color: #bc1823;           /* Chữ chuyển sang đỏ đậm */\n"
"    border: 1px solid #df9da2;\n"
"}")
        self.label_quanlyhocvien_2.setObjectName("label_quanlyhocvien_2")
        self.Malop1 = QtWidgets.QLabel(parent=self.widget_2)
        self.Malop1.setGeometry(QtCore.QRect(600, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Malop1.setFont(font)
        self.Malop1.setText("")
        self.Malop1.setObjectName("Malop1")
        self.btnxoa = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnxoa.setGeometry(QtCore.QRect(600, 700, 171, 51))
        self.btnxoa.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.btnxoa.setObjectName("btnxoa")
        self.txtSearch1 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.txtSearch1.setGeometry(QtCore.QRect(280, 110, 461, 31))
        self.txtSearch1.setStyleSheet("QLineEdit {\n"
"    border: 1px solid black;\n"
"}\n"
"")
        self.txtSearch1.setObjectName("txtSearch1")
        self.search1 = QtWidgets.QPushButton(parent=self.widget_2)
        self.search1.setGeometry(QtCore.QRect(770, 110, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.search1.setFont(font)
        self.search1.setStyleSheet("background:rgb(221, 221, 221)")
        self.search1.setObjectName("search1")
        self.btnthem = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnthem.setGeometry(QtCore.QRect(140, 700, 171, 51))
        self.btnthem.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.btnthem.setObjectName("btnthem")
        self.edit = QtWidgets.QPushButton(parent=self.widget_2)
        self.edit.setGeometry(QtCore.QRect(370, 700, 171, 51))
        self.edit.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.edit.setObjectName("edit")
        self.btnsua_2 = QtWidgets.QPushButton(parent=self.widget_2)
        self.btnsua_2.setGeometry(QtCore.QRect(840, 700, 171, 51))
        self.btnsua_2.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.btnsua_2.setObjectName("btnsua_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.themhv.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "New Row"))
        item = self.themhv.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "STT"))
        item = self.themhv.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ID"))
        item = self.themhv.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Họ và tên"))
        item = self.themhv.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Ngày sinh"))
        item = self.themhv.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Giới tính"))
        item = self.themhv.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Địa chỉ"))
        item = self.themhv.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Số điện thoại"))
        item = self.themhv.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Email"))
        item = self.themhv.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "Ngày đăng kí"))
        __sortingEnabled = self.themhv.isSortingEnabled()
        self.themhv.setSortingEnabled(False)
        self.themhv.setSortingEnabled(__sortingEnabled)
        self.label_12.setText(_translate("Dialog", "DANH SÁCH LỚP:"))
        self.Button_return.setText(_translate("Dialog", "⇦"))
        self.label_quanlyhocvien_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Quản lý HỌC VIÊN</span></p></body></html>"))
        self.btnxoa.setText(_translate("Dialog", "XÓA"))
        self.txtSearch1.setPlaceholderText(_translate("Dialog", "Nhập tên hoặc ID"))
        self.search1.setText(_translate("Dialog", "Tìm"))
        self.btnthem.setText(_translate("Dialog", "THÊM"))
        self.edit.setText(_translate("Dialog", "SỬA"))
        self.btnsua_2.setText(_translate("Dialog", "LƯU"))
