# Form implementation generated from reading ui file 'chonkythi.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(859, 529)
        Dialog.setProperty("pixmao", "")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 861, 521))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.frame.setObjectName("frame")
        self.trove1 = QtWidgets.QPushButton(parent=self.frame)
        self.trove1.setGeometry(QtCore.QRect(300, 360, 231, 51))
        self.trove1.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.trove1.setObjectName("trove1")
        self.giuakhoa = QtWidgets.QPushButton(parent=self.frame)
        self.giuakhoa.setGeometry(QtCore.QRect(300, 170, 231, 51))
        self.giuakhoa.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.giuakhoa.setObjectName("giuakhoa")
        self.cuoikhoa = QtWidgets.QPushButton(parent=self.frame)
        self.cuoikhoa.setGeometry(QtCore.QRect(300, 260, 231, 51))
        self.cuoikhoa.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 10pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.cuoikhoa.setObjectName("cuoikhoa")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(40, 20, 771, 41))
        self.label.setStyleSheet("QLabel {\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    \n"
"    background-color: #BC1823;\n"
"    \n"
"    color: white;\n"
"    padding: 5px;\n"
"}\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(630, 300, 151, 131))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("chonkythiframe.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(220, 90, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Malop1 = QtWidgets.QLabel(parent=self.frame)
        self.Malop1.setGeometry(QtCore.QRect(460, 90, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Malop1.setFont(font)
        self.Malop1.setText("")
        self.Malop1.setObjectName("Malop1")
        self.label.raise_()
        self.trove1.raise_()
        self.giuakhoa.raise_()
        self.cuoikhoa.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.Malop1.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.trove1.setText(_translate("Dialog", "Trở về"))
        self.giuakhoa.setText(_translate("Dialog", "Giữa khóa"))
        self.cuoikhoa.setText(_translate("Dialog", "Cuối khóa"))
        self.label_4.setText(_translate("Dialog", "NHẬP ĐIỂM THI LỚP: "))
