# Form implementation generated from reading ui file 'file_ui/dslopp.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1161, 771)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1161, 771))
        self.widget.setStyleSheet("background: white;\n"
"")
        self.widget.setObjectName("widget")
        self.dslopqli = QtWidgets.QTableWidget(parent=self.widget)
        self.dslopqli.setGeometry(QtCore.QRect(60, 110, 1041, 521))
        self.dslopqli.setStyleSheet("QTableWidget {\n"
"    font: 75 9pt \"MS Shell Dlg 2\";\n"
"    background-color: white;\n"
"    alternate-background-color:#ffecee;\n"
"    gridline-color: black;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"    padding: 4px;\n"
"    border: 1px solid black;\n"
"}\n"
"\n"
"")
        self.dslopqli.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.dslopqli.setProperty("showDropIndicator", True)
        self.dslopqli.setDragDropOverwriteMode(True)
        self.dslopqli.setAlternatingRowColors(True)
        self.dslopqli.setShowGrid(True)
        self.dslopqli.setObjectName("dslopqli")
        self.dslopqli.setColumnCount(8)
        self.dslopqli.setRowCount(29)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.dslopqli.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.dslopqli.setItem(0, 0, item)
        self.dslopqli.horizontalHeader().setDefaultSectionSize(110)
        self.dslopqli.horizontalHeader().setSortIndicatorShown(False)
        self.dslopqli.horizontalHeader().setStretchLastSection(True)
        self.dslopqli.verticalHeader().setVisible(False)
        self.dslopqli.verticalHeader().setDefaultSectionSize(37)
        self.dslopqli.verticalHeader().setSortIndicatorShown(False)
        self.addhv = QtWidgets.QPushButton(parent=self.widget)
        self.addhv.setGeometry(QtCore.QRect(360, 660, 191, 51))
        self.addhv.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 9pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.addhv.setObjectName("addhv")
        self.taokythi = QtWidgets.QPushButton(parent=self.widget)
        self.taokythi.setGeometry(QtCore.QRect(900, 660, 191, 51))
        self.taokythi.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 9pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.taokythi.setObjectName("taokythi")
        self.label_12 = QtWidgets.QLabel(parent=self.widget)
        self.label_12.setGeometry(QtCore.QRect(370, 60, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.qlyhcphi = QtWidgets.QPushButton(parent=self.widget)
        self.qlyhcphi.setGeometry(QtCore.QRect(90, 660, 191, 51))
        self.qlyhcphi.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 9pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.qlyhcphi.setObjectName("qlyhcphi")
        self.return_2 = QtWidgets.QPushButton(parent=self.widget)
        self.return_2.setGeometry(QtCore.QRect(30, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.return_2.setFont(font)
        self.return_2.setStyleSheet("QPushButton {\n"
"    /* Màu nền và viền */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 8px; /* Tăng bo góc một chút cho hợp với chữ to */\n"
"    \n"
"    /* Chữ: In đậm, Cỡ 25pt, Font Segoe UI */\n"
"    color: #bc1823;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    \n"
"    /* Đệm thêm khoảng trống xung quanh chữ */\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8d7da;\n"
"    border: 2px solid #bc1823; /* Viền dày hơn khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        icon = QtGui.QIcon.fromTheme("\\u2b05")
        self.return_2.setIcon(icon)
        self.return_2.setIconSize(QtCore.QSize(25, 25))
        self.return_2.setObjectName("return_2")
        self.xemdshv = QtWidgets.QPushButton(parent=self.widget)
        self.xemdshv.setGeometry(QtCore.QRect(630, 660, 191, 51))
        self.xemdshv.setStyleSheet("QPushButton {\n"
"    /* Font Segoe UI, cỡ chữ 10pt, độ đậm 700 (Bold) */\n"
"    font: 700 9pt \"Segoe UI\"; \n"
"    color: white;\n"
"    background-color: #bc1823;\n"
"    border-radius: 8px; /* Bo góc 8px theo yêu cầu của bạn */\n"
"    padding: 12px;      /* Padding 12px theo yêu cầu của bạn */\n"
"    border: 1px solid #ccc;\n"
"    text-transform: uppercase; /* In hoa toàn bộ chữ để trông quyền lực hơn (tùy chọn) */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffecee;\n"
"    color: #bc1823; /* Chữ đỏ đậm trên nền hồng nhạt sẽ đẹp hơn đen */\n"
"    border: 2px solid #df9da2;\n"
"}")
        self.xemdshv.setObjectName("xemdshv")
        self.label_quanlyhocvien_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_quanlyhocvien_2.setGeometry(QtCore.QRect(0, 10, 1161, 41))
        self.label_quanlyhocvien_2.setStyleSheet("QLabel {\n"
"    /* Màu nền đỏ đậm thương hiệu của Trầm */\n"
"    background-color: #bc1823;\n"
"    \n"
"    /* Chữ trắng, in hoa và đậm (Bold 700) */\n"
"    color: white;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"    \n"
"    /* Bo góc và viền để khớp với Dashboard */\n"
"    border-radius: 8px;\n"
"    border: 1px solid #bc1823;\n"
"    \n"
"    /* Căn giữa chữ tuyệt đối */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột vào để giao diện sinh động hơn */\n"
"QLabel:hover {\n"
"    background-color: #ffecee; /* Đổi sang nền hồng nhạt */\n"
"    color: #bc1823;           /* Chữ chuyển sang đỏ đậm */\n"
"    border: 1px solid #df9da2;\n"
"}")
        self.label_quanlyhocvien_2.setObjectName("label_quanlyhocvien_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.dslopqli.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "New Row"))
        item = self.dslopqli.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "STT"))
        item = self.dslopqli.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Mã lớp"))
        item = self.dslopqli.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Tên lớp"))
        item = self.dslopqli.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Khóa học"))
        item = self.dslopqli.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Giáo viên"))
        item = self.dslopqli.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Thời gian"))
        item = self.dslopqli.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Sĩ số"))
        item = self.dslopqli.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Trạng thái"))
        __sortingEnabled = self.dslopqli.isSortingEnabled()
        self.dslopqli.setSortingEnabled(False)
        self.dslopqli.setSortingEnabled(__sortingEnabled)
        self.addhv.setText(_translate("Dialog", "THÊM HỌC VIÊN"))
        self.taokythi.setText(_translate("Dialog", "TẠO KỲ THI"))
        self.label_12.setText(_translate("Dialog", "DANH SÁCH LỚP HỌC HIỆN TẠI"))
        self.qlyhcphi.setText(_translate("Dialog", "Quản lý học phí"))
        self.return_2.setText(_translate("Dialog", "⇦"))
        self.xemdshv.setText(_translate("Dialog", "DANH SÁCH HỌC VIÊN"))
        self.label_quanlyhocvien_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:11pt;\">Quản lý HỌC VIÊN</span></p></body></html>"))
