# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\Quanlyhoadongtgt\CSDL\file_ui\manhinhquanlykhoahoc.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 602)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 941, 581))
        self.widget.setStyleSheet("QWidget#widget {\n"
"    background-color: #ffffff;\n"
"    border: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.label_quanlykhoahoc = QtWidgets.QLabel(parent=self.widget)
        self.label_quanlykhoahoc.setGeometry(QtCore.QRect(10, 50, 781, 41))
        self.label_quanlykhoahoc.setStyleSheet("QLabel {\n"
"    /* Màu nền đỏ đậm thương hiệu của Trầm */\n"
"    background-color: #bc1823;\n"
"    \n"
"    /* Chữ trắng, in hoa và đậm (Bold 700) */\n"
"    color: white;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"    \n"
"    /* Bo góc và viền để khớp với Dashboard */\n"
"    border-radius: 8px;\n"
"    border: 1px solid #bc1823;\n"
"    \n"
"    /* Căn giữa chữ tuyệt đối */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột vào để giao diện sinh động hơn */\n"
"QLabel:hover {\n"
"    background-color: #ffecee; /* Đổi sang nền hồng nhạt */\n"
"    color: #bc1823;           /* Chữ chuyển sang đỏ đậm */\n"
"    border: 1px solid #df9da2;\n"
"}")
        self.label_quanlykhoahoc.setObjectName("label_quanlykhoahoc")
        self.table_quanly = QtWidgets.QTableWidget(parent=self.widget)
        self.table_quanly.setGeometry(QtCore.QRect(10, 100, 491, 231))
        self.table_quanly.setStyleSheet("QTableWidget {\n"
"    /* Viền ngoài bảng */\n"
"    border: 3px solid #bc1823;\n"
"    border-radius: 15px;\n"
"    background-color: white;\n"
"    \n"
"    /* KẺ DÒNG: Màu của đường lưới giữa các ô */\n"
"    gridline-color: #bc1823; \n"
"    \n"
"    font: 700 10pt \"Segoe UI\";\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Thanh tiêu đề (STT, Mã lớp...) */\n"
"QHeaderView::section {\n"
"    background-color: #bc1823; /* Nền đỏ đậm */\n"
"    color: white;              /* Chữ trắng */\n"
"    border: 1px solid white;   /* Kẻ dọc màu trắng giữa các tiêu đề cho rõ */\n"
"    padding: 5px;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* Màu nền xen kẽ các hàng (giống ảnh image_5cecb1) */\n"
"QTableWidget {\n"
"    alternate-background-color: #ffecee; /* Màu hồng nhạt */\n"
"}\n"
"\n"
"/* Khi nhấn chọn một ô */\n"
"QTableWidget::item:selected {\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"}")
        self.table_quanly.setWordWrap(True)
        self.table_quanly.setObjectName("table_quanly")
        self.table_quanly.setColumnCount(5)
        self.table_quanly.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly.setHorizontalHeaderItem(4, item)
        self.table_quanly.horizontalHeader().setVisible(True)
        self.table_quanly.horizontalHeader().setDefaultSectionSize(100)
        self.table_quanly.horizontalHeader().setHighlightSections(True)
        self.table_quanly.horizontalHeader().setStretchLastSection(True)
        self.table_quanly.verticalHeader().setVisible(False)
        self.table_quanly.verticalHeader().setHighlightSections(True)
        self.tableskills = QtWidgets.QTableView(parent=self.widget)
        self.tableskills.setGeometry(QtCore.QRect(510, 100, 271, 231))
        self.tableskills.setStyleSheet("QFrame {\n"
"    /* Bo góc 15px và viền đỏ 3px giống hệt bảng danh sách */\n"
"    border: 3px solid #bc1823;\n"
"    border-radius: 18px;\n"
"    background-color: white;\n"
"}")
        self.tableskills.setObjectName("tableskills")
        self.tableskills.horizontalHeader().setDefaultSectionSize(80)
        self.label_kynangdaotao = QtWidgets.QLabel(parent=self.widget)
        self.label_kynangdaotao.setGeometry(QtCore.QRect(520, 110, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.label_kynangdaotao.setFont(font)
        self.label_kynangdaotao.setStyleSheet("QLabel {\n"
"    /* Màu nền đỏ đậm thương hiệu của Trầm */\n"
"    background-color: #bc1823;\n"
"    \n"
"    /* Chữ trắng, in hoa và đậm (Bold 700) */\n"
"    color: white;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"    \n"
"    /* Bo góc và viền để khớp với Dashboard */\n"
"    border-radius: 8px;\n"
"    border: 1px solid #bc1823;\n"
"    \n"
"    /* Căn giữa chữ tuyệt đối */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột vào để giao diện sinh động hơn */\n"
"QLabel:hover {\n"
"    background-color: #ffecee; /* Đổi sang nền hồng nhạt */\n"
"    color: #bc1823;           /* Chữ chuyển sang đỏ đậm */\n"
"    border: 1px solid #df9da2;\n"
"}")
        self.label_kynangdaotao.setObjectName("label_kynangdaotao")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 360, 181, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_them = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_them.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        self.pushButton_them.setObjectName("pushButton_them")
        self.horizontalLayout.addWidget(self.pushButton_them)
        self.pushButton_sua = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_sua.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        self.pushButton_sua.setObjectName("pushButton_sua")
        self.horizontalLayout.addWidget(self.pushButton_sua)
        self.pushButton_xoa = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_xoa.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        self.pushButton_xoa.setObjectName("pushButton_xoa")
        self.horizontalLayout.addWidget(self.pushButton_xoa)
        self.pushButton_quaylai = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_quaylai.setGeometry(QtCore.QRect(10, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quaylai.setFont(font)
        self.pushButton_quaylai.setStyleSheet("QPushButton {\n"
"    /* Màu nền và viền */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 8px; /* Tăng bo góc một chút cho hợp với chữ to */\n"
"    \n"
"    /* Chữ: In đậm, Cỡ 25pt, Font Segoe UI */\n"
"    color: #bc1823;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    \n"
"    /* Đệm thêm khoảng trống xung quanh chữ */\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8d7da;\n"
"    border: 2px solid #bc1823; /* Viền dày hơn khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        icon = QtGui.QIcon.fromTheme("\\u2b05")
        self.pushButton_quaylai.setIcon(icon)
        self.pushButton_quaylai.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_quaylai.setObjectName("pushButton_quaylai")
        self.pushButton_c01 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_c01.setGeometry(QtCore.QRect(520, 160, 251, 31))
        self.pushButton_c01.setStyleSheet("QPushButton {\n"
"    /* Nền đỏ rất nhạt (light red/pinkish) */\n"
"    background-color: #fff0f1; \n"
"    /* Viền đỏ nhạt để định hình nút */\n"
"    border: 1px solid #fbcaca;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ màu đỏ đậm (theo tông màu chủ đạo #bc1823) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Khi di chuột: Nền đỏ rõ hơn một chút */\n"
"    background-color: #ffdada;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Khi nhấn: Nền chuyển hẳn sang đỏ đậm, chữ trắng */\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"}")
        self.pushButton_c01.setObjectName("pushButton_c01")
        self.pushButton_c02 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_c02.setGeometry(QtCore.QRect(520, 200, 251, 31))
        self.pushButton_c02.setStyleSheet("QPushButton {\n"
"    /* Nền đỏ rất nhạt (light red/pinkish) */\n"
"    background-color: #fff0f1; \n"
"    /* Viền đỏ nhạt để định hình nút */\n"
"    border: 1px solid #fbcaca;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ màu đỏ đậm (theo tông màu chủ đạo #bc1823) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Khi di chuột: Nền đỏ rõ hơn một chút */\n"
"    background-color: #ffdada;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Khi nhấn: Nền chuyển hẳn sang đỏ đậm, chữ trắng */\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"}")
        self.pushButton_c02.setObjectName("pushButton_c02")
        self.pushButton_c03 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_c03.setGeometry(QtCore.QRect(520, 240, 251, 31))
        self.pushButton_c03.setStyleSheet("QPushButton {\n"
"    /* Nền đỏ rất nhạt (light red/pinkish) */\n"
"    background-color: #fff0f1; \n"
"    /* Viền đỏ nhạt để định hình nút */\n"
"    border: 1px solid #fbcaca;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ màu đỏ đậm (theo tông màu chủ đạo #bc1823) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Khi di chuột: Nền đỏ rõ hơn một chút */\n"
"    background-color: #ffdada;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Khi nhấn: Nền chuyển hẳn sang đỏ đậm, chữ trắng */\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"}")
        self.pushButton_c03.setObjectName("pushButton_c03")
        self.pushButton_c05 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_c05.setGeometry(QtCore.QRect(520, 280, 251, 31))
        self.pushButton_c05.setStyleSheet("QPushButton {\n"
"    /* Nền đỏ rất nhạt (light red/pinkish) */\n"
"    background-color: #fff0f1; \n"
"    /* Viền đỏ nhạt để định hình nút */\n"
"    border: 1px solid #fbcaca;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ màu đỏ đậm (theo tông màu chủ đạo #bc1823) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Khi di chuột: Nền đỏ rõ hơn một chút */\n"
"    background-color: #ffdada;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Khi nhấn: Nền chuyển hẳn sang đỏ đậm, chữ trắng */\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"}")
        self.pushButton_c05.setObjectName("pushButton_c05")
        self.pushButton_listening = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_listening.setGeometry(QtCore.QRect(810, 150, 111, 31))
        self.pushButton_listening.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_listening.setObjectName("pushButton_listening")
        self.pushButton_speaking = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_speaking.setGeometry(QtCore.QRect(810, 190, 111, 31))
        self.pushButton_speaking.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_speaking.setObjectName("pushButton_speaking")
        self.pushButton_reading = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_reading.setGeometry(QtCore.QRect(810, 230, 111, 31))
        self.pushButton_reading.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_reading.setObjectName("pushButton_reading")
        self.pushButton_writing = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_writing.setGeometry(QtCore.QRect(810, 270, 111, 31))
        self.pushButton_writing.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_writing.setObjectName("pushButton_writing")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 995, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_quanlykhoahoc.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Quản lý khoá học</span></p></body></html>"))
        item = self.table_quanly.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_quanly.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_quanly.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_quanly.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table_quanly.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.table_quanly.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.table_quanly.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.table_quanly.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "KHOÁ HỌC"))
        item = self.table_quanly.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CẤP ĐỘ"))
        item = self.table_quanly.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "HỌC PHÍ"))
        item = self.table_quanly.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TRẠNG THÁI"))
        self.label_kynangdaotao.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">KHOÁ HỌC ĐÀO TẠO</span></p><p align=\"center\"><span style=\" font-size:11pt;\"><br/></span></p></body></html>"))
        self.pushButton_them.setText(_translate("MainWindow", "Thêm"))
        self.pushButton_sua.setText(_translate("MainWindow", "Sửa"))
        self.pushButton_xoa.setText(_translate("MainWindow", "Xoá"))
        self.pushButton_quaylai.setText(_translate("MainWindow", "⇦"))
        self.pushButton_c01.setText(_translate("MainWindow", "English Communication Basic (C01)"))
        self.pushButton_c02.setText(_translate("MainWindow", "English Starter (C02)"))
        self.pushButton_c03.setText(_translate("MainWindow", "Cambridge Mover (C03) && Flyer (C04)"))
        self.pushButton_c05.setText(_translate("MainWindow", "IELTS 5.0 (C05) && IELTS 6.0 (C06)"))
        self.pushButton_listening.setText(_translate("MainWindow", "LISTENING"))
        self.pushButton_speaking.setText(_translate("MainWindow", "SPEAKING"))
        self.pushButton_reading.setText(_translate("MainWindow", "READING"))
        self.pushButton_writing.setText(_translate("MainWindow", "WRITING"))
