# Form implementation generated from reading ui file 'C:\Users\Admin\PycharmProjects\Quanlyhoadongtgt\giao_dien\manhinhquanlyuser.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1084, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1081, 651))
        self.widget.setStyleSheet("QWidget#widget {\n"
"    background-color: #ffffff;\n"
"    border: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.label_quanlyuser = QtWidgets.QLabel(parent=self.widget)
        self.label_quanlyuser.setGeometry(QtCore.QRect(180, 90, 631, 41))
        self.label_quanlyuser.setStyleSheet("QLabel {\n"
"    /* Màu nền đỏ đậm thương hiệu của Trầm */\n"
"    background-color: #bc1823;\n"
"    \n"
"    /* Chữ trắng, in hoa và đậm (Bold 700) */\n"
"    color: white;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    text-transform: uppercase;\n"
"    \n"
"    /* Bo góc và viền để khớp với Dashboard */\n"
"    border-radius: 8px;\n"
"    border: 1px solid #bc1823;\n"
"    \n"
"    /* Căn giữa chữ tuyệt đối */\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"    padding: 8px;\n"
"}\n"
"\n"
"/* Hiệu ứng khi di chuột vào để giao diện sinh động hơn */\n"
"QLabel:hover {\n"
"    background-color: #ffecee; /* Đổi sang nền hồng nhạt */\n"
"    color: #bc1823;           /* Chữ chuyển sang đỏ đậm */\n"
"    border: 1px solid #df9da2;\n"
"}")
        self.label_quanlyuser.setObjectName("label_quanlyuser")
        self.table_quanly4 = QtWidgets.QTableWidget(parent=self.widget)
        self.table_quanly4.setGeometry(QtCore.QRect(180, 150, 631, 301))
        self.table_quanly4.setStyleSheet("QTableWidget {\n"
"    /* Viền ngoài bảng */\n"
"    border: 3px solid #bc1823;\n"
"    border-radius: 15px;\n"
"    background-color: white;\n"
"    \n"
"    /* KẺ DÒNG: Màu của đường lưới giữa các ô */\n"
"    gridline-color: #bc1823; \n"
"    \n"
"    font: 700 10pt \"Segoe UI\";\n"
"    outline: none;\n"
"}\n"
"\n"
"/* Thanh tiêu đề (STT, Mã lớp...) */\n"
"QHeaderView::section {\n"
"    background-color: #bc1823; /* Nền đỏ đậm */\n"
"    color: white;              /* Chữ trắng */\n"
"    border: 1px solid white;   /* Kẻ dọc màu trắng giữa các tiêu đề cho rõ */\n"
"    padding: 5px;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"/* Màu nền xen kẽ các hàng (giống ảnh image_5cecb1) */\n"
"QTableWidget {\n"
"    alternate-background-color: #ffecee; /* Màu hồng nhạt */\n"
"}\n"
"\n"
"/* Khi nhấn chọn một ô */\n"
"QTableWidget::item:selected {\n"
"    background-color: #bc1823;\n"
"    color: white;\n"
"}")
        self.table_quanly4.setWordWrap(True)
        self.table_quanly4.setObjectName("table_quanly4")
        self.table_quanly4.setColumnCount(5)
        self.table_quanly4.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_quanly4.setHorizontalHeaderItem(4, item)
        self.table_quanly4.horizontalHeader().setVisible(True)
        self.table_quanly4.horizontalHeader().setDefaultSectionSize(120)
        self.table_quanly4.horizontalHeader().setHighlightSections(True)
        self.table_quanly4.horizontalHeader().setStretchLastSection(True)
        self.table_quanly4.verticalHeader().setVisible(False)
        self.table_quanly4.verticalHeader().setHighlightSections(True)
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 470, 181, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_them3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_them3.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        self.pushButton_them3.setObjectName("pushButton_them3")
        self.horizontalLayout.addWidget(self.pushButton_them3)
        self.pushButton_sua2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_sua2.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        self.pushButton_sua2.setObjectName("pushButton_sua2")
        self.horizontalLayout.addWidget(self.pushButton_sua2)
        self.pushButton_xoa2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_xoa2.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        self.pushButton_xoa2.setObjectName("pushButton_xoa2")
        self.horizontalLayout.addWidget(self.pushButton_xoa2)
        self.pushButton_quaylai3 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_quaylai3.setGeometry(QtCore.QRect(180, 40, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_quaylai3.setFont(font)
        self.pushButton_quaylai3.setStyleSheet("QPushButton {\n"
"    /* Màu nền và viền */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 8px; /* Tăng bo góc một chút cho hợp với chữ to */\n"
"    \n"
"    /* Chữ: In đậm, Cỡ 25pt, Font Segoe UI */\n"
"    color: #bc1823;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 20pt;\n"
"    font-weight: bold;\n"
"    \n"
"    /* Đệm thêm khoảng trống xung quanh chữ */\n"
"    padding: 5px 20px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f8d7da;\n"
"    border: 2px solid #bc1823; /* Viền dày hơn khi di chuột */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}")
        icon = QtGui.QIcon.fromTheme("\\u2b05")
        self.pushButton_quaylai3.setIcon(icon)
        self.pushButton_quaylai3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_quaylai3.setObjectName("pushButton_quaylai3")
        self.pushButton_dangxuat4 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_dangxuat4.setGeometry(QtCore.QRect(730, 470, 91, 31))
        self.pushButton_dangxuat4.setStyleSheet("QPushButton {\n"
"    /* Màu nền hồng nhạt phối với viền hồng đậm hơn một chút */\n"
"    background-color: #ffecee; \n"
"    border: 1px solid #df9da2;\n"
"    border-radius: 6px;\n"
"    \n"
"    /* Chữ đỏ đậm nhưng cỡ nhỏ lại (9pt thay vì 10-11pt) */\n"
"    color: #bc1823;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    \n"
"    /* Không in hoa toàn bộ để trông nhẹ nhàng hơn */\n"
"    padding: 5px 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    /* Hiệu ứng khi di chuột vào: Nền đậm hơn xíu */\n"
"    background-color: #f8d7da;\n"
"    border: 1px solid #bc1823;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #df9da2;\n"
"    color: white;\n"
"}\n"
"")
        self.pushButton_dangxuat4.setObjectName("pushButton_dangxuat4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_quanlyuser.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt;\">Quản lý TÀI KHOẢN NGƯỜI DÙNG</span></p></body></html>"))
        item = self.table_quanly4.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.table_quanly4.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.table_quanly4.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.table_quanly4.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.table_quanly4.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.table_quanly4.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.table_quanly4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID "))
        item = self.table_quanly4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "USERNAME"))
        item = self.table_quanly4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "SỐ ĐIỆN THOẠI"))
        item = self.table_quanly4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "EMAIL"))
        item = self.table_quanly4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "TRẠNG THÁI"))
        self.pushButton_them3.setText(_translate("MainWindow", "Thêm"))
        self.pushButton_sua2.setText(_translate("MainWindow", "Sửa"))
        self.pushButton_xoa2.setText(_translate("MainWindow", "Xoá"))
        self.pushButton_quaylai3.setText(_translate("MainWindow", "⇦"))
        self.pushButton_dangxuat4.setText(_translate("MainWindow", "Đăng xuất"))
